export const USER_DETAILS = "USER_DETAILS";
export const MEDITATION_RECORDING_LIST = "MEDITATION_RECORDING_LIST";
export const REGISTER_GLUCOSE_LEVEL = "REGISTER_GLUCOSE_LEVEL";
export const GET_GLUCOSE_LEVEL_FORDAY = "GET_GLUCOSE_LEVEL_FORDAY";
export const GET_GLUCOSE_LEVEL_FORWEEK = "GET_GLUCOSE_LEVEL_FORWEEK";
export const GET_GLUCOSE_LEVEL_FORMONTH = "GET_GLUCOSE_LEVEL_FORMONTH";
export const RESET_STORE = "RESET_STORE";
export const REGISTER_BMI = "REGISTER_BMI";
export const REGISTER_BLOOD_PRESSURE = "REGISTER_BLOOD_PRESSURE"
export const ADD_REMAINDER = "ADD_REMAINDER";
export const GET_REMAINDER = "GET_REMAINDER";

//App
export const SET_SAFE_AREA = "SET_SAFE_AREA";
export const SET_VISIBLE_TAB = "SET_VISIBLE_TAB";
export const SET_BOTTOM_TAB = "SET_BOTTOM_TAB";
